#!/usr/bin/env python3
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
META = ROOT / 'config' / 'report_metadata.yaml'
OUT = ROOT / 'report' / 'sections' / '00_metadata.tex'

REQUIRED = ['course_name', 'college', 'major_class', 'student_id', 'student_name', 'instructor', 'report_date']
OPTIONAL = ['github_repo', 'school', 'latex_engine', 'tex_distribution']


def parse_simple_yaml(path: Path):
    data = {}
    if not path.exists():
        raise FileNotFoundError(f'Metadata file not found: {path}')
    for raw in path.read_text(encoding='utf-8').splitlines():
        line = raw.strip()
        if not line or line.startswith('#') or ':' not in line:
            continue
        key, val = line.split(':', 1)
        key = key.strip()
        val = val.strip()
        if val.startswith(('"', "'")) and val.endswith(('"', "'")):
            val = val[1:-1]
        data[key] = val
    return data


def tex_escape(s: str) -> str:
    if s is None or s == '':
        s = '待填写'
    repl = {
        '\\': r'\textbackslash{}',
        '&': r'\&', '%': r'\%', '$': r'\$', '#': r'\#',
        '_': r'\_', '{': r'\{', '}': r'\}', '~': r'\textasciitilde{}',
        '^': r'\textasciicircum{}',
    }
    return ''.join(repl.get(ch, ch) for ch in s)


def macro_name(key: str) -> str:
    mapping = {
        'course_name': 'ReportCourseName',
        'college': 'ReportCollege',
        'major_class': 'ReportMajorClass',
        'student_id': 'ReportStudentId',
        'student_name': 'ReportStudentName',
        'instructor': 'ReportInstructor',
        'report_date': 'ReportDate',
        'github_repo': 'ReportGithubRepo',
        'school': 'ReportSchool',
        'latex_engine': 'ReportLatexEngine',
        'tex_distribution': 'ReportTexDistribution',
    }
    return mapping[key]


def main():
    data = parse_simple_yaml(META)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        '% Auto-generated by scripts/sync_report_metadata.py',
        '% Do not edit this file directly. Edit config/report_metadata.yaml instead.',
    ]
    for key in REQUIRED + OPTIONAL:
        val = data.get(key, '待填写')
        lines.append(f'\\newcommand{{\\{macro_name(key)}}}{{{tex_escape(val)}}}')
    OUT.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(f'Generated {OUT.relative_to(ROOT)} from {META.relative_to(ROOT)}')

if __name__ == '__main__':
    main()
